swagger: "2.0"
info:
  description: "My simple flask application service"
  version: "1.0.0"
  title: "My flask"
  contact:
    email: "barlesh8@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v2"
tags:
  - name: "basic"
    description: "Everything about Basic stuff"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
  - name: "basic1"
    description: "Access to first basic stuff"
  - name: "basic2"
    description: "Access to first basic stuff 2"
    externalDocs:
      description: "Find out more about our basic functions"
      url: "http://swagger.io"
schemes:
  - "https"
  - "http"
paths:
  /basic:
    post:
      tags:
        - "basic"
      summary: "Add a basic stuff"
      description: ""
      operationId: "app.addBasic"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Basic object that needs to be added to the basic stuff"
          schema:
            $ref: "#/definitions/Basic"
      responses:
        "405":
          description: "Invalid input"
      # security:
      #   - petstore_auth:
      #       - "write:pets"
      #       - "read:pets"

definitions:
  Basic:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      description:
        type: "string"
        example: "whatever u want"
